sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/NameGenScreen.kt
