sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
sed -i '$d' app/src/main/java/com/example/ui/screens/UsernameGenScreen.kt
