#!/bin/bash
START=$(grep -n "Text(\"Name Parts\"" app/src/main/java/com/example/ui/screens/NameGenScreen.kt | cut -d: -f1)
END=$(grep -n -A 100 "Text(\"Name Parts\"" app/src/main/java/com/example/ui/screens/NameGenScreen.kt | grep -n "ADVANCED OPTIONS" | cut -d: -f1)

# Because we are piping to grep -n again, the second line number is relative.
# Let's just use awk.

awk '
/Text\("Name Parts"/ {
    in_parts = 1
    print "                    Text(\"Name Parts\", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)"
    print "                    "
    print "                    if (mode == \"Full Name\" || mode == \"First Name\") {"
    print "                        OutlinedTextField("
    print "                            value = customFirst,"
    print "                            onValueChange = { customFirst = it },"
    print "                            label = { Text(\"First Name\") },"
    print "                            placeholder = { Text(\"Random First Name\") },"
    print "                            modifier = Modifier.fillMaxWidth(),"
    print "                            singleLine = true,"
    print "                            shape = RoundedCornerShape(12.dp),"
    print "                            trailingIcon = {"
    print "                                IconButton(onClick = { "
    print "                                    val gen = ModernGenerators.generateName(\"First Name\", gender, country, style, lastNameCategory, false, \"\", \"\", \"\", 1, nameLength, initialsOnly, excludeDuplicates, noRepeat).firstOrNull()?.name ?: \"\""
    print "                                    customFirst = gen"
    print "                                }) {"
    print "                                    Icon(Icons.Default.Refresh, \"Regenerate First Name\")"
    print "                                }"
    print "                            }"
    print "                        )"
    print "                    }"
    print ""
    print "                    if (mode == \"Full Name\" || mode == \"Middle Name\") {"
    print "                        if (mode == \"Full Name\") {"
    print "                            Row(verticalAlignment = Alignment.CenterVertically) {"
    print "                                Checkbox("
    print "                                    checked = includeMiddle,"
    print "                                    onCheckedChange = { includeMiddle = it },"
    print "                                    colors = CheckboxDefaults.colors(checkedColor = MaterialTheme.colorScheme.primary)"
    print "                                )"
    print "                                Text(\"Include Middle Name\", style = MaterialTheme.typography.bodyMedium)"
    print "                            }"
    print "                        }"
    print "                        "
    print "                        if (includeMiddle || mode == \"Middle Name\") {"
    print "                            OutlinedTextField("
    print "                                value = customMiddle,"
    print "                                onValueChange = { customMiddle = it },"
    print "                                label = { Text(\"Middle Name\") },"
    print "                                placeholder = { Text(\"Random Middle Name\") },"
    print "                                modifier = Modifier.fillMaxWidth(),"
    print "                                singleLine = true,"
    print "                                shape = RoundedCornerShape(12.dp),"
    print "                                trailingIcon = {"
    print "                                    IconButton(onClick = { "
    print "                                        val gen = ModernGenerators.generateName(\"Middle Name\", gender, country, style, lastNameCategory, true, \"\", \"\", \"\", 1, nameLength, initialsOnly, excludeDuplicates, noRepeat).firstOrNull()?.name ?: \"\""
    print "                                        customMiddle = gen"
    print "                                    }) {"
    print "                                        Icon(Icons.Default.Refresh, \"Regenerate Middle Name\")"
    print "                                    }"
    print "                                }"
    print "                            )"
    print "                        }"
    print "                    }"
    print ""
    print "                    if (mode == \"Full Name\" || mode == \"Last Name\") {"
    print "                        var showCategoryMenu by remember { mutableStateOf(false) }"
    print "                        "
    print "                        OutlinedTextField("
    print "                            value = customLast,"
    print "                            onValueChange = { customLast = it },"
    print "                            label = { Text(\"Last Name\") },"
    print "                            placeholder = { Text(\"Random $lastNameCategory Last Name\") },"
    print "                            modifier = Modifier.fillMaxWidth(),"
    print "                            singleLine = true,"
    print "                            shape = RoundedCornerShape(12.dp),"
    print "                            trailingIcon = {"
    print "                                Row {"
    print "                                    IconButton(onClick = { "
    print "                                        val gen = ModernGenerators.generateName(\"Last Name\", gender, country, style, lastNameCategory, false, \"\", \"\", \"\", 1, nameLength, initialsOnly, excludeDuplicates, noRepeat).firstOrNull()?.name ?: \"\""
    print "                                        customLast = gen"
    print "                                    }) {"
    print "                                        Icon(Icons.Default.Refresh, \"Regenerate Last Name\")"
    print "                                    }"
    print "                                    Box {"
    print "                                        IconButton(onClick = { showCategoryMenu = true }) {"
    print "                                            Icon(Icons.Default.ArrowDropDown, \"Select Category\")"
    print "                                        }"
    print "                                        DropdownMenu("
    print "                                            expanded = showCategoryMenu,"
    print "                                            onDismissRequest = { showCategoryMenu = false }"
    print "                                        ) {"
    print "                                            lastNameCategories.forEach { cat ->"
    print "                                                DropdownMenuItem("
    print "                                                    text = { Text(cat) },"
    print "                                                    onClick = {"
    print "                                                        lastNameCategory = cat"
    print "                                                        showCategoryMenu = false"
    print "                                                    }"
    print "                                                )"
    print "                                            }"
    print "                                        }"
    print "                                    }"
    print "                                }"
    print "                            }"
    print "                        )"
    print "                    }"
    print "                }"
    print "            }"
    next
}
/ADVANCED OPTIONS/ {
    in_parts = 0
}
!in_parts { print $0 }
' app/src/main/java/com/example/ui/screens/NameGenScreen.kt > temp.kt
mv temp.kt app/src/main/java/com/example/ui/screens/NameGenScreen.kt
